cat <<EOF | kubectl apply -f -
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "<KEY VAULT>"
  namespace: default
spec:
  provider: azure
  secretObjects:  
  - secretName: amc-dev-kv-secrets     
    type: Opaque                                            
    data:
    - objectName: amc-dev-env 
      key: sc-amc-dev-env  
    - objectName: amc-dev-flask-app
      key: sc-amc-dev-flask-app  
    - objectName: amc-dev-redirect-uri
      key: sc-amc-dev-redirect-uri      
    - objectName: amc-dev-org-url
      key: sc-amc-dev-org-url
    - objectName: amc-dev-application-client-id
      key: sc-amc-dev-application-client-id
    - objectName: amc-dev-application-secret-key
      key: sc-amc-dev-application-secret-key
    - objectName: amc-dev-okta-redirect-uri
      key: sc-amc-dev-okta-redirect-uri
    - objectName: amc-dev-az-acc-name
      key: sc-amc-dev-az-acc-name
    - objectName: amc-dev-az-primary-key
      key: sc-amc-dev-az-primary-key
    - objectName: amc-dev-az-container
      key: sc-amc-dev-az-container
    - objectName: amc-dev-az-acc-sas
      key: sc-amc-dev-az-acc-sas
    - objectName: amc-dev-refresh-token-ui
      key: sc-amc-dev-refresh-token-ui
    - objectName: amc-dev-client-id-ui
      key: sc-amc-dev-client-id-ui
    - objectName: amc-dev-client-secret-ui
      key: sc-amc-dev-client-secret-ui
    - objectName: amc-dev-profileid
      key: sc-amc-dev-profileid
    - objectName: amc-dev-advertiserid
      key: sc-amc-dev-advertiserid
    - objectName: amc-dev-shared-client-secret
      key: sc-amc-dev-shared-client-secret
    - objectName: amc-dev-tenetid
      key: sc-amc-dev-tenetid
    - objectName: amc-dev-cc-api-clientid
      key: sc-amc-dev-cc-api-clientid
    - objectName: amc-dev-cc-api-client-secret
      key: sc-amc-dev-cc-api-client-secret
    - objectName: amc-dev-subscription-id
      key: sc-amc-dev-subscription-id
    - objectName: amc-dev-rg
      key: sc-amc-dev-rg
    - objectName: amc-dev-adf
      key: sc-amc-dev-adf
    - objectName: amc-dev-sql-server
      key: sc-amc-dev-sql-server
    - objectName: amc-dev-sql-db
      key: sc-amc-dev-sql-db
    - objectName: amc-dev-sql-driver
      key: sc-amc-dev-sql-driver
    - objectName: amc-dev-okta-key
      key: sc-amc-dev-okta-key
    - objectName: amc-dev-okta-secret
      key: sc-amc-dev-okta-secret
    - objectName: amc-dev-sql-password
      key: sc-amc-dev-sql-password
    - objectName: amc-dev-sql-uid
      key: sc-amc-dev-sql-uid
    - objectName: amc-dev-reckitt-okta-api-token
      key: sc-amc-dev-reckitt-okta-api-token
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: "<KEY VAULT>"
    objects: |
      array:
        - |
          objectName: amc-dev-env
          objectType: secret
          objectVersion: ""
        - |
          objectName: amc-dev-flask-app
          objectType: secret
          objectVersion: ""
        - |
          objectName: amc-dev-redirect-uri
          objectType: secret
          objectVersion: ""
        - |
          objectName: amc-dev-org-url
          objectType: secret
          objectVersion: ""
        - |
          objectName: amc-dev-application-client-id
          objectType: secret
          objectVersion: ""
        - |
          objectName: amc-dev-application-secret-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: amc-dev-okta-redirect-uri
          objectType: secret
          objectVersion: ""
        - |
          objectName: amc-dev-az-acc-name
          objectType: secret
          objectVersion: ""
        - |
          objectName: amc-dev-az-primary-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: amc-dev-az-container
          objectType: secret
          objectVersion: ""
        - |
          objectName: amc-dev-az-acc-sas
          objectType: secret
          objectVersion: ""
        - |
          objectName: amc-dev-refresh-token-ui
          objectType: secret
          objectVersion: ""
        - |
          objectName: amc-dev-client-id-ui
          objectType: secret
          objectVersion: ""
        - |
          objectName: amc-dev-client-secret-ui
          objectType: secret
          objectVersion: ""
        - |
          objectName: amc-dev-profileid
          objectType: secret
          objectVersion: ""
        - |
          objectName: amc-dev-advertiserid
          objectType: secret
          objectVersion: ""
        - |
          objectName: amc-dev-shared-client-secret
          objectType: secret
          objectVersion: ""
        - |
          objectName: amc-dev-tenetid
          objectType: secret
          objectVersion: ""
        - |
          objectName: amc-dev-cc-api-clientid
          objectType: secret
          objectVersion: ""
        - |
          objectName: amc-dev-cc-api-client-secret
          objectType: secret
          objectVersion: ""
        - |
          objectName: amc-dev-subscription-id
          objectType: secret
          objectVersion: ""
        - |
          objectName: amc-dev-rg
          objectType: secret
          objectVersion: ""
        - |
          objectName: amc-dev-adf
          objectType: secret
          objectVersion: ""
        - |
          objectName: amc-dev-sql-server
          objectType: secret
          objectVersion: ""
        - |
          objectName: amc-dev-sql-db
          objectType: secret
          objectVersion: ""
        - |
          objectName: amc-dev-sql-driver
          objectType: secret
          objectVersion: ""
        - |
          objectName: amc-dev-okta-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: amc-dev-okta-secret
          objectType: secret
          objectVersion: ""
        - |
          objectName: amc-dev-sql-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: amc-dev-sql-uid
          objectType: secret
          objectVersion: ""
        - |
          objectName: amc-dev-reckitt-okta-api-token
          objectType: secret
          objectVersion: ""
    tenantID: "<TENANTID>"
EOF