# Default values for servercharts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: rbmatrixamc.azurecr.io/amc-backend
  pullPolicy: Always
  tag: latest

imagePullSecrets: 
  - name: acr-amc-login
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:  
  type: ClusterIP
  port: 80 
  containerPort: 5000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []


resources:
  limits:
    cpu: 200m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 500Mi

controller:
  autoscaling:
    minReplicas: 2
    maxReplicas: 10
    targetAverageUtilization: 80

nodeSelector: {}

tolerations: []

affinity: {}
