apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "amc-backend.fullname" . }}
  labels:
    {{- include "amc-backend.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "amc-backend.fullname" . }}
  minReplicas: {{ .Values.controller.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.controller.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
     name: cpu
     target:
       type: Utilization
       averageUtilization: {{ .Values.controller.autoscaling.targetAverageUtilization }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.controller.autoscaling.targetAverageUtilization }} 
